version: '3'
services:
   mysql-db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./.data:/var/lib/mysql"
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpw'
      MYSQL_DATABASE: 'postdb'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'userpw'
    ports:
      - "3306:3306"